### ISSUE TITLE
First click is a mine

### ISSUE THREAD

**Issue by wsasaki01** [wsasaki01/mini-mines#1]
Currently, the square the user first presses could be a mine, randomly.

- [x] Re-generate mine list if mine falls on user's current square

**Comment by wsasaki01** [comment]
Didn't have to completely regenerate; whenever the function generates a new mine, it checks it against the current position, just as it compares it against previously created mines.

**Comment by Aaronfishe** [comment]
![image](https://user-images.githubusercontent.com/93435242/235728544-9e1b5060-d9df-4b01-85af-361304f992d6.png)

Had this issue happen again in firefox browser on easy, clicked the centre tile first and there was a mine

Edit: have reproduced this bug twice by following the same steps, once on firefox again and once on windows binary
